ARGS Python-version=3.12-slim
FROM python:${Python-version}
WORKDIR /app
COPY requirements.txt .
RUN pip install  -r requirements.txt
COPY ./test11 .
EXPOSE 8000
ENTRYPOINT [ "python" ]
ENV DEBUG=True
CMD [ "manage.py", "runserver_plus", "0.0.0.0:8000" ]

#docker build -t <image_name> -e DEBUG=True --build-arg Python-version=3.11-slim .
