resolver 127.0.0.11

#the web_$ are just to explain these concepts so its a bad practise rather we use (docker compose up -d --scale django=3) also it automatically creates the web_1, web_2, web_3 containers and we can use these names in nginx.conf file to load balance the traffic between these containers.

upstream django_backend {
    ip_hash;
    server web_1:8000 weight=3; # web means the name of the service defined in docker-compose.yml
    server web_2:8000 weight=1;
}
upstream api_backend {
    ip_hash;
    server api_1:8000 weight=3;
    server api_2:8000 weight=1;
}
map $host $backend {
    #default backend:8080;
    saikumar.me django_backend;
    api.saikumar.me api_backend;
}

server{
    listen 80;
    server_name saikumar.me api.saikumar.me;
    location / {
        root   /usr/share/nginx/html/main;
        index  index.html;
       # proxy_pass http://$backend;
       # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       # proxy_set_header Host $http_host;
    }
}
#to store app data use usr/src/app
