#we only use reolver when we use map the reuqest to the backend_servers
#we use reolver to communicate between the containers in the same network and it is used to resolve the domain names to IP addresses. In this case, we are using the default DNS server provided by Docker which is

#the web_$ are just to explain these concepts so its a bad practise rather we use (docker compose up -d --scale django=3) also it automatically creates the web_1, web_2, web_3 containers and we can use these names in nginx.conf file to load balance the traffic between these containers.

http{

resolver 127.0.0.11
# A/B split
split_clients "${remote_addr}" $django_backend {
    50% django_backend_v1;
    *   django_backend_v2;
}

#rate limit uses leaky bucket algo
limit_req_zone $binary_remote_addr zone=api_delay:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=admin_panel:10m rate=1r/s;

# Upstreams
upstream django_backend_v1 {
    server web_v1_1:8000; # web means the name of the service defined in docker-compose.yml
    server web_v1_2:8000; #here even the server name and using same port wont make the system cuz inside the conatiner they have their own ip so its conatiner:port each continer have their own IP address inside image
}

upstream django_backend_v2 {
    server web_v2_1:8000;
    server web_v2_2:8000;
}

upstream api_backend {
    server api_1:8000;
    server api_2:8000;
}

# Routing
map $host $backend {
    saikumar.me $django_backend;
    api.saikumar.me api_backend;
}

# Cache
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;

server {
    listen 80;
    server_name saikumar.me api.saikumar.me;

    location / {
        limit_req  zone=api_delay burst=20 nodelay;#burst is the maximum number of requests that can be queued when the rate limit is exceeded, nodelay means that the requests will be processed immediately without any delay when the burst limit is not exceeded.
        proxy_pass http://$backend;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;

        proxy_cache my_cache;
        proxy_cache_min_uses 3;
        proxy_cache_valid 200 302 10m;
        proxy_cache_valid 404 1m;
        proxy_cache_methods GET;
        proxy_cache_key "$scheme$request_method$host$request_uri";

        add_header X-Cache-Status $upstream_cache_status always;
    }
    location /admin/login/ {
        limit_req zone=admin_login burst=1 nodelay;
        limit_req_status 429;
        proxy_pass http://django_backend;
    }

}

}
